
let deferredPrompt=null;if('serviceWorker'in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('./service-worker.js').catch(err=>console.log(err));});}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=document.getElementById('installBtn');b.style.display='inline-block';});
document.addEventListener('click',async e=>{if(e.target&&e.target.id==='installBtn'&&deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;e.target.style.display='none';}});
let inventoryData=[],stocktake={},settings={lowStockThreshold:10,sessionName:''},db;const $=id=>document.getElementById(id);
function toNumberOrNull(v){if(v===''||v===null||v===undefined)return null;if(typeof v==='string'){const t=v.trim();if(!t||t.toUpperCase()==='#N/A')return null;const n=Number(t.replace(/,/g,''));return Number.isFinite(n)?n:null}const n=Number(v);return Number.isFinite(n)?n:null}
function cleanText(v){if(v===null||v===undefined)return'';const t=String(v).trim();return t.toUpperCase()==='#N/A'?'':t}
function formatNumber(n){return Number(n||0).toLocaleString()}
function getStatus(item){const qty=Number(item.QtyOnHand||0),min=item.MinLevel;if(qty<=0)return'STOCKOUT';if(min!==null&&min!==undefined&&min!==''&&qty<Number(min))return'LOW STOCK';if(qty<Number(settings.lowStockThreshold||0))return'REVIEW';return'OK'}
function statusBadge(s){if(s==='STOCKOUT')return'<span class="pill pill-danger">STOCKOUT</span>';if(s==='LOW STOCK')return'<span class="pill pill-warning">LOW STOCK</span>';if(s==='REVIEW')return'<span class="pill pill-warning">REVIEW</span>';return'<span class="pill pill-ok">OK</span>'}
function rowClass(s){if(s==='STOCKOUT')return'stockout';if(s==='LOW STOCK'||s==='REVIEW')return'low-stock';return'ok-row'}
function normalizeItem(raw){const stock=raw.StockCode??raw['Stock Code']??raw['SAP Material'];const desc=raw.Description??raw['Material Description']??raw['Item Description'];if(!stock||!desc)return null;return{StockCode:cleanText(stock),Description:cleanText(desc),AlternateKey:cleanText(raw.AlternateKey??raw['old stkcode']),QtyOnHand:toNumberOrNull(raw.QtyOnHand??raw['Stock on hand ']??raw['Stock on hand']??raw['Qty'])??0,DefaultBin:cleanText(raw.DefaultBin??raw['Bin location']??raw['Default Bin']??raw['Bin']),MinLevel:toNumberOrNull(raw.MinLevel??raw['minimum QTY']??raw['Min']),MaxLevel:toNumberOrNull(raw.MaxLevel??raw['maximum QTY']??raw['Max']),UnitCost:toNumberOrNull(raw.UnitCost??raw['Unit cost ']??raw['Unit cost']),TotalValue:toNumberOrNull(raw.TotalValue??raw['Total value']),Department:cleanText(raw.Department??raw['Department ']),Machine:cleanText(raw.Machine??raw['Machine ']),Currency:cleanText(raw.Currency)}}
function downloadExcel(rows,sheetName,filename){const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheetName);XLSX.writeFile(wb,filename)}
const request=indexedDB.open('InventoryPWA_DB_MOBILE',1);request.onerror=e=>console.log('IndexedDB error:',e.target.errorCode);request.onupgradeneeded=e=>{db=e.target.result;if(!db.objectStoreNames.contains('inventory'))db.createObjectStore('inventory',{keyPath:'StockCode'});if(!db.objectStoreNames.contains('stocktake'))db.createObjectStore('stocktake',{keyPath:'StockCode'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});};request.onsuccess=e=>{db=e.target.result;loadAll();};
function tx(name,mode='readonly'){return db.transaction([name],mode).objectStore(name)}function saveInventory(){const s=tx('inventory','readwrite');s.clear();inventoryData.forEach(it=>s.put(it))}function saveStocktake(){const s=tx('stocktake','readwrite');s.clear();Object.entries(stocktake).forEach(([StockCode,obj])=>s.put({StockCode,...obj}))}function saveSettings(){const s=tx('settings','readwrite');s.put({key:'lowStockThreshold',value:settings.lowStockThreshold});s.put({key:'sessionName',value:settings.sessionName})}
function loadAll(){tx('inventory').getAll().onsuccess=e=>{inventoryData=e.target.result||[];tx('stocktake').getAll().onsuccess=e2=>{stocktake={};(e2.target.result||[]).forEach(r=>stocktake[r.StockCode]={CountedQty:r.CountedQty??null,UpdatedAt:r.UpdatedAt??null});tx('settings').getAll().onsuccess=e3=>{(e3.target.result||[]).forEach(r=>settings[r.key]=r.value);$('lowStockThreshold').value=settings.lowStockThreshold??10;$('sessionName').value=settings.sessionName??'';renderAll();};};};}
document.querySelectorAll('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{const tab=btn.dataset.tab;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.tab-section').forEach(sec=>sec.style.display=sec.id===tab?'block':'none');renderAll();}));
$('goToAlertsBtn').addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab==='alerts'));document.querySelectorAll('.tab-section').forEach(sec=>sec.style.display=sec.id==='alerts'?'block':'none');renderAlertsTable();});
$('excelUpload').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const data=new Uint8Array(e.target.result),workbook=XLSX.read(data,{type:'array'}),preferredSheet=workbook.SheetNames.find(n=>n.trim().toUpperCase()==='MR01')||workbook.SheetNames[0],sheet=workbook.Sheets[preferredSheet],raw=XLSX.utils.sheet_to_json(sheet,{defval:''}),normalized=raw.map(normalizeItem).filter(Boolean),existing={...stocktake};inventoryData=normalized;stocktake={};inventoryData.forEach(it=>{if(existing[it.StockCode])stocktake[it.StockCode]=existing[it.StockCode];});saveInventory();saveStocktake();renderAll();alert(`Excel imported successfully from sheet: ${preferredSheet}`);}catch(err){console.error(err);alert('Import failed. Use your current SAP export format.');}};reader.readAsArrayBuffer(file);});
$('loadSampleBtn').addEventListener('click',async()=>{const res=await fetch('./sample-data.json');const raw=await res.json();inventoryData=raw.map(normalizeItem).filter(Boolean);stocktake={};saveInventory();saveStocktake();renderAll();alert('Sample data loaded.');});
$('searchInput').addEventListener('input',renderPreviewTable);$('stocktakeFilter').addEventListener('input',renderStocktakeTable);$('alertSearch').addEventListener('input',renderAlertsTable);$('alertFilter').addEventListener('change',renderAlertsTable);$('lowStockThreshold').addEventListener('input',()=>{settings.lowStockThreshold=Number($('lowStockThreshold').value||0);saveSettings();renderAll();});
$('clearAllBtn').addEventListener('click',()=>{if(!confirm('Clear ALL inventory + stocktake data on this device?'))return;inventoryData=[];stocktake={};settings.sessionName='';saveInventory();saveStocktake();saveSettings();renderAll();});
$('exportInventoryBtn').addEventListener('click',()=>{if(inventoryData.length===0)return alert('No inventory data to export.');downloadExcel(inventoryData,'Inventory','InventoryData_CurrentFormat.xlsx');});
$('exportAlertsBtn').addEventListener('click',exportAlertsExcel);$('addItemBtn').addEventListener('click',()=>{const newItem=normalizeItem({StockCode:$('newStockCode').value,Description:$('newDescription').value,'old stkcode':$('newAlternateKey').value,'Stock on hand':$('newQtyOnHand').value,'Bin location':$('newDefaultBin').value,'minimum QTY':$('newMinLevel').value,'maximum QTY':$('newMaxLevel').value});if(!newItem)return alert('Material and Description are required.');const idx=inventoryData.findIndex(x=>x.StockCode===newItem.StockCode);if(idx>=0)inventoryData[idx]={...inventoryData[idx],...newItem};else inventoryData.push(newItem);saveInventory();renderAll();$('newStockCode').value='';$('newDescription').value='';$('newAlternateKey').value='';$('newQtyOnHand').value='0';$('newDefaultBin').value='';$('newMinLevel').value='';$('newMaxLevel').value='';});
$('saveSessionNameBtn').addEventListener('click',()=>{settings.sessionName=$('sessionName').value.trim();saveSettings();renderAll();});$('markAllUncountedBtn').addEventListener('click',()=>{if(!confirm('Set ALL CountedQty to blank?'))return;stocktake={};saveStocktake();renderStocktakeTable();renderAll();});$('exportVarianceBtn').addEventListener('click',exportVarianceExcel);$('exportFullCountBtn').addEventListener('click',exportFullCountExcel);$('exportCycleCountBtn').addEventListener('click',exportCycleCountSheet);$('exportStocktakeBtn').addEventListener('click',exportVarianceExcel);
function matchesQuery(it,q){if(!q)return true;return((it.StockCode||'').toLowerCase().includes(q)||(it.Description||'').toLowerCase().includes(q)||(it.AlternateKey||'').toLowerCase().includes(q)||(it.Department||'').toLowerCase().includes(q)||(it.Machine||'').toLowerCase().includes(q))}
function alertItems(){return inventoryData.filter(it=>getStatus(it)!=='OK')}
function renderAll(){renderPreviewTable();renderItemsTable();renderStocktakeTable();renderAlertsTable();renderDashboardAlertsTable();updateDashboard()}
function renderPreviewTable(){const tbody=document.querySelector('#previewTable tbody');tbody.innerHTML='';const q=$('searchInput').value.toLowerCase().trim();inventoryData.filter(it=>matchesQuery(it,q)).slice(0,250).forEach(it=>{const s=getStatus(it),tr=document.createElement('tr');tr.className=rowClass(s);tr.innerHTML=`<td class="mono">${escapeHtml(it.StockCode)}</td><td>${escapeHtml(it.Description)}</td><td class="right mono">${it.QtyOnHand??0}</td><td class="hide-mobile">${escapeHtml(it.DefaultBin||'')}</td><td class="right mono">${it.MinLevel??''}</td><td>${statusBadge(s)}</td>`;tbody.appendChild(tr);});}
function renderDashboardAlertsTable(){const tbody=document.querySelector('#dashboardAlertsTable tbody');tbody.innerHTML='';const order={'STOCKOUT':0,'LOW STOCK':1,'REVIEW':2};alertItems().slice().sort((a,b)=>order[getStatus(a)]-order[getStatus(b)]).slice(0,10).forEach(it=>{const s=getStatus(it),tr=document.createElement('tr');tr.className=rowClass(s);tr.innerHTML=`<td class="mono">${escapeHtml(it.StockCode)}</td><td>${escapeHtml(it.Description)}</td><td class="right mono">${it.QtyOnHand??0}</td><td class="right mono">${it.MinLevel??''}</td><td class="hide-mobile">${escapeHtml(it.Department||'')}</td><td>${statusBadge(s)}</td>`;tbody.appendChild(tr);});}
function renderAlertsTable(){const tbody=document.querySelector('#alertsTable tbody');tbody.innerHTML='';const filter=$('alertFilter').value,q=$('alertSearch').value.toLowerCase().trim(),order={'STOCKOUT':0,'LOW STOCK':1,'REVIEW':2};alertItems().filter(it=>matchesQuery(it,q)).filter(it=>{const s=getStatus(it);if(filter==='stockout')return s==='STOCKOUT';if(filter==='low')return s==='LOW STOCK';if(filter==='review')return s==='REVIEW';return true;}).sort((a,b)=>order[getStatus(a)]-order[getStatus(b)]).forEach(it=>{const s=getStatus(it),tr=document.createElement('tr');tr.className=rowClass(s);tr.innerHTML=`<td class="mono">${escapeHtml(it.StockCode)}</td><td>${escapeHtml(it.Description)}</td><td class="right mono">${it.QtyOnHand??0}</td><td class="right mono">${it.MinLevel??''}</td><td class="hide-mobile">${escapeHtml(it.Department||'')}</td><td class="hide-mobile">${escapeHtml(it.Machine||'')}</td><td>${statusBadge(s)}</td>`;tbody.appendChild(tr);});}
function renderItemsTable(){const tbody=document.querySelector('#itemsTable tbody');tbody.innerHTML='';[...inventoryData].sort((a,b)=>String(a.StockCode).localeCompare(String(b.StockCode))).forEach(it=>{const s=getStatus(it),tr=document.createElement('tr');tr.className=rowClass(s);tr.innerHTML=`<td class="mono">${escapeHtml(it.StockCode)}</td><td>${escapeHtml(it.Description)}</td><td class="right mono">${it.QtyOnHand??0}</td><td class="hide-mobile">${escapeHtml(it.DefaultBin||'')}</td><td>${statusBadge(s)}</td><td class="center"><button data-del="${escapeAttr(it.StockCode)}" class="ghost" style="margin:0;padding:6px 10px;">Del</button></td>`;tbody.appendChild(tr);});tbody.querySelectorAll('button[data-del]').forEach(btn=>btn.addEventListener('click',()=>{const code=btn.getAttribute('data-del');if(!confirm(`Delete item ${code}?`))return;inventoryData=inventoryData.filter(x=>x.StockCode!==code);delete stocktake[code];saveInventory();saveStocktake();renderAll();}));}
function renderStocktakeTable(){const tbody=document.querySelector('#stocktakeTable tbody');tbody.innerHTML='';const q=$('stocktakeFilter').value.toLowerCase().trim();[...inventoryData].filter(it=>matchesQuery(it,q)).sort((a,b)=>String(a.StockCode).localeCompare(String(b.StockCode))).forEach(it=>{const counted=stocktake[it.StockCode]?.CountedQty??null,variance=counted===null?'':(counted-(it.QtyOnHand||0)),s=getStatus(it),tr=document.createElement('tr');tr.className=rowClass(s);tr.innerHTML=`<td class="mono">${escapeHtml(it.StockCode)}</td><td>${escapeHtml(it.Description)}</td><td class="right mono">${it.QtyOnHand??0}</td><td class="right"><input inputmode="numeric" style="max-width:120px" type="number" data-count="${escapeAttr(it.StockCode)}" value="${counted??''}" /></td><td class="right mono" data-var="${escapeAttr(it.StockCode)}">${variance}</td><td class="hide-mobile">${escapeHtml(it.DefaultBin||'')}</td><td>${statusBadge(s)}</td>`;tbody.appendChild(tr);});tbody.querySelectorAll('input[data-count]').forEach(inp=>inp.addEventListener('input',()=>{const code=inp.getAttribute('data-count'),countedQty=toNumberOrNull(inp.value);if(countedQty===null)delete stocktake[code];else stocktake[code]={CountedQty:countedQty,UpdatedAt:new Date().toISOString()};saveStocktake();const it=inventoryData.find(x=>x.StockCode===code),varCell=tbody.querySelector(`[data-var="${cssEscape(code)}"]`);if(varCell)varCell.textContent=countedQty===null?'':(countedQty-(it?.QtyOnHand||0));updateDashboard();}));}
function updateDashboard(){$('totalItems').innerText=formatNumber(inventoryData.length);$('totalQty').innerText=formatNumber(inventoryData.reduce((s,it)=>s+(it.QtyOnHand||0),0));$('stockoutCount').innerText=formatNumber(inventoryData.filter(it=>getStatus(it)==='STOCKOUT').length);$('lowStockCount').innerText=formatNumber(inventoryData.filter(it=>getStatus(it)==='LOW STOCK').length);$('inventoryValue').innerText=formatNumber(inventoryData.reduce((s,it)=>s+(it.TotalValue||((it.UnitCost||0)*(it.QtyOnHand||0))),0));$('stockoutValue').innerText=formatNumber(inventoryData.filter(it=>getStatus(it)==='STOCKOUT').reduce((s,it)=>s+(it.UnitCost||0),0));$('countedLines').innerText=formatNumber(Object.keys(stocktake).length);$('varianceLines').innerText=formatNumber(Object.keys(stocktake).filter(code=>{const it=inventoryData.find(x=>x.StockCode===code),counted=stocktake[code]?.CountedQty;return counted!==null&&counted!==undefined&&(counted-(it?.QtyOnHand||0))!==0;}).length);}
function exportVarianceExcel(){if(inventoryData.length===0)return alert('No inventory loaded.');const rows=[];Object.entries(stocktake).forEach(([code,obj])=>{const it=inventoryData.find(x=>x.StockCode===code);if(!it||obj.CountedQty===null||obj.CountedQty===undefined)return;const variance=obj.CountedQty-(it.QtyOnHand||0);if(variance===0)return;rows.push({Session:settings.sessionName||'',SAP_Material:it.StockCode,Material_Description:it.Description,Bin_location:it.DefaultBin||'',Department:it.Department||'',Machine:it.Machine||'',SystemQty:it.QtyOnHand||0,CountedQty:obj.CountedQty,Variance:variance,Status:getStatus(it),UpdatedAt:obj.UpdatedAt||''});});if(rows.length===0)return alert('No variances found yet.');downloadExcel(rows,'Variances','Stocktake_Variances.xlsx');}
function exportFullCountExcel(){if(inventoryData.length===0)return alert('No inventory loaded.');const rows=inventoryData.map(it=>{const counted=stocktake[it.StockCode]?.CountedQty??null;return{Session:settings.sessionName||'',SAP_Material:it.StockCode,Material_Description:it.Description,Bin_location:it.DefaultBin||'',Department:it.Department||'',Machine:it.Machine||'',Stock_on_hand:it.QtyOnHand||0,minimum_QTY:it.MinLevel??'',maximum_QTY:it.MaxLevel??'',Status:getStatus(it),CountedQty:counted,Variance:counted===null?null:(counted-(it.QtyOnHand||0))};});downloadExcel(rows,'FullCount','Stocktake_FullCount.xlsx');}
function exportCycleCountSheet(){if(inventoryData.length===0)return alert('No inventory loaded.');const rows=inventoryData.map(it=>({SAP_Material:it.StockCode,Material_Description:it.Description,Bin_location:it.DefaultBin||'',Department:it.Department||'',Machine:it.Machine||'',Stock_on_hand:it.QtyOnHand||0,CountedQty:'',minimum_QTY:it.MinLevel??'',maximum_QTY:it.MaxLevel??'',Status:getStatus(it)}));downloadExcel(rows,'CycleCount','CycleCountSheet.xlsx');}
function exportAlertsExcel(){const rows=alertItems().map(it=>({SAP_Material:it.StockCode,Material_Description:it.Description,Bin_location:it.DefaultBin||'',Department:it.Department||'',Machine:it.Machine||'',Stock_on_hand:it.QtyOnHand||0,minimum_QTY:it.MinLevel??'',maximum_QTY:it.MaxLevel??'',Status:getStatus(it)}));if(rows.length===0)return alert('No stock alerts found.');downloadExcel(rows,'StockAlerts','Stock_Alerts_Report.xlsx');}
function escapeHtml(str){return String(str).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}function escapeAttr(str){return escapeHtml(str)}function cssEscape(str){return String(str).replace(/"/g,'\\"')}
